language: go
go:
  - "1.11.x"

dist: xenial

matrix:
  include:
    - os: linux
      services:
        - docker
    - os: osx
      # Do not start osx build for PR
      if: type != pull_request
      osx_image: xcode8

install:
  - go get -u github.com/FiloSottile/vendorcheck
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $GOPATH/bin v1.13.2

script:
  - make test
  - make lint