scripts_directory: "$HOME/.skywire-updater/scripts"

active_update_checkers:
  naive:
    notify_url: "http://localhost:8989/update"
    kind: "naive"

updaters:
  custom:
    kind: "custom"

services:
  skywire-messaging-server:
    official_name: "skywire-messaging"
    local_name: "msgsrv"
    update_script: "skywire-messaging.sh"
    check_script: "generic-service-check-update.sh"
    check_script_interpreter: "/bin/bash"
    check_script_timeout: "20m"
    update_script_interpreter: "/bin/bash"
    update_script_timeout: "20m"
    update_script_extra_arguments:
      - "-c localhost:9094 -a localhost:8084 -s test-server"
    active_update_checker: "naive"
    repository: "/watercompany/skywire-messaging"
    updater: "custom"

  skywire-messaging-client:
    official_name: "skywire-messaging"
    local_name: "simple-client"
    update_script: "skywire-messaging.sh"
    check_script: "generic-service-check-update.sh"
    check_script_interpreter: "/bin/bash"
    check_script_timeout: "20m"
    update_script_interpreter: "/bin/bash"
    update_script_timeout: "20m"
    update_script_extra_arguments:
    active_update_checker: "naive"
    repository: "/watercompany/skywire-messaging"
    updater: "custom"

  skywire-messaging-discovery:
    official_name: "skywire-messaging"
    local_name: "msgdiscovery"
    update_script: "skywire-messaging.sh"
    check_script: "generic-service-check-update.sh"
    check_script_interpreter: "/bin/bash"
    check_script_timeout: "20m"
    update_script_interpreter: "/bin/bash"
    update_script_timeout: "20m"
    update_script_extra_arguments:
      - "-p 9090"
    active_update_checker: "naive"
    repository: "/watercompany/skywire-messaging"
    updater: "custom"
