# The default configuration.

paths:
  db-file: "/usr/local/skywire-updater/db.json"
  scripts-path: "/usr/local/skywire-updater/scripts"

interfaces:
  addr: ":7280"
  enable-rest: true
  enable-rpc: true

defaults:
  main-branch: "master"
  interpreter: "/bin/bash"

services:
  skywire:
    repo: "github.com/watercompany/skywire"
    main-process: "skywire-node"
    checker:
      type: "github-release"
    updater:
      type: "script"
      script: "update/skywire"
      env:
        - "BIN_DIR=/usr/local/skywire/bin"
        - "APP_DIR=/usr/local/skywire/apps/bin"

  skywire-updater:
    repo: "github.com/watercompany/skywire-updater"
    main-process: "skywire-updater"
    checker:
      type: "github-release"
    updater:
      type: "script"
      script: "update/to-release"
      envs:
        - "BIN_DIR=/usr/local/skywire-updater/bin"

  skycoin:
    repo: "github.com/skycoin/skycoin"
    main-process: "skycoin"
    checker:
      type: "github-release"
    updater:
      type: "script"
      script: "update/to-release"
      envs:
        - "BIN_DIR=/usr/local/skycoin/bin"