default:
  main-branch: "master"
  interpreter: "/bin/bash"
  envs: - "BIN_DIR=./bin" # TODO: properly define.
        - "APP_DIR=./bin" # TODO: properly define.

services:
  skywire:
    repo: "github.com/watercompany/skywire"
    main-process: "skywire-node"
    checker:
      type: "script"
      script: "check/bin_diff"
    updater:
      type: "script"
      script: "update/skywire"

  skywire-updater:
    repo: "github.com/watercompany/skywire-updater"
    main-process: "skywire-updater"
    checker:
      type: "github_release"
    updater:
      type: "script"
      script: "update/to_release"

  skycoin:
    repo: "github.com/skycoin/skycoin"
    main-process: "skycoin"
    checker:
      type: "github_release"
    updater:
      type: "script"
      script: "update/to_release"