# The default configuration.

paths:
  db-file: "db.json"
  scripts-path: "scripts"

interfaces:
  addr: ":7280"
  enable-rest: true
  enable-rpc: true

defaults:
  main-branch: "master"
  interpreter: "/bin/bash"
  envs:
    - "BIN_DIR=./bin" # TODO: properly define.
    - "APP_DIR=./bin" # TODO: properly define.

services:
  skywire:
    repo: "github.com/watercompany/skywire"
    main-process: "skywire-node"
    checker:
      type: "script"
      script: "check/bin-diff"
    updater:
      type: "script"
      script: "update/skywire"

  skywire-updater:
    repo: "github.com/watercompany/skywire-updater"
    main-process: "skywire-updater"
    checker:
      type: "github-release"
    updater:
      type: "script"
      script: "update/to-release"

  skycoin:
    repo: "github.com/skycoin/skycoin"
    main-process: "skycoin"
    checker:
      type: "github-release"
    updater:
      type: "script"
      script: "update/to-release"